name: One-off: send at 17:50 AR today

on:
  schedule:
    # 20:50 UTC = 17:50 America/Argentina/Cordoba
    - cron: "50 20 * * *"
  workflow_dispatch: {}   # permite ejecutarlo manualmente

jobs:
  call_twilio_function:
    runs-on: ubuntu-latest
    steps:
      - name: Print current UTC time (debug)
        run: echo "Runner UTC time: $(date -u)"
      - name: Call Twilio Function
        run: |
          set -e
          curl -f -sS -X POST \
            -H "Content-Type: application/json" \
            --retry 3 --retry-delay 5 \
            -d "{\"token\":\"${{ secrets.REMINDER_TOKEN }}\"}" \
            "${{ vars.REMINDER_URL }}"
