name: Daily appointment reminders

on:
  schedule:
    # 11:00 UTC = 08:00 America/Argentina/Cordoba (UTC-3, sin DST)
    - cron: "0 11 * * *"
  workflow_dispatch: {}   # Permite ejecutarlo manualmente para probar

jobs:
  call_twilio_function:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time (debug)
        run: |
          echo "Runner UTC time: $(date -u)"
      - name: Call Twilio Function
        run: |
          set -e
          curl -f -sS -X POST \
            -H "Content-Type: application/json" \
            --retry 3 --retry-delay 5 \
            -d "{\"token\":\"${{ secrets.REMINDER_TOKEN }}\"}" \
            "${{ vars.REMINDER_URL }}"
